name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
          if [ ${{ github.event_name == 'pull_request' }} ]; then
            python -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src -v tests/ | tee pytest-coverage.txt;
              # get coverage percentage from outputted pytest-coverage.txt
              coverage=$(grep 'TOTAL'  pytest-coverage.txt | awk '{print $4}')
              # remove % for comparison, using suffix-removing expansion
              coverage=${coverage%"%"}
              if [ $coverage -lt ${{ vars.MINIMUM_COVERAGE }} ]; then
                echo ${{ github.event.number }};
                echo 'Coverage less than threshold';
              fi
            else
              python -m pytest -v tests/;
          fi
        shell: bash
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml